name: Build RcloneMounter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'
        
    - name: Display dotnet version
      run: dotnet --info
        
    - name: Restore dependencies
      run: dotnet restore RcloneMounter.csproj
      
    - name: Build
      run: dotnet build RcloneMounter.csproj --configuration Release --no-restore
      
    - name: Publish
      run: dotnet publish RcloneMounter.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true
    
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        name: RcloneMounter-${{ github.run_number }}
        tag_name: v0.1.${{ github.run_number }}
        draft: false
        prerelease: false
        files: |
          bin/Release/net6.0-windows/win-x64/publish/RcloneMounter.exe
      env:
        GITHUB_TOKEN: ${{ github.token }} 